### ISSUE TITLE
How to display the data you created in unity

### ISSUE THREAD

**Issue by liaohuanxuan** [thalesfm/unity-nerf#14] opened 2024-01-04 08:39 UTC
Thank you for your work!
I created a svox format` .npz` for the data，but I don't know how to put this `.npz` file into unity to display it.
Can you offer some solutions?

**Comment by thalesfm** [comment] 2024-02-16 17:55
Duplicate of #16

**Comment by thalesfm** [comment] 2024-02-16 17:56
Duplicate of #16

**Closed** 2024-02-16 18:01 UTC
Labels: question
