### ISSUE TITLE
How to perform Binary serialization ?

### ISSUE THREAD

**Issue by AvishkarArjan** [thalesfm/unity-nerf#17] opened 2024-02-20 13:29 UTC
You've done a great work here. Maybe if you could refer me any sources for me to understand the conversion+binary serialization process, so that maybe i could work on a script of my own, it would be a great help. Thanks .

**Comment by thalesfm** [comment] 2024-02-23 18:08
Duplicate of #15

**Closed by thalesfm** 2024-02-23 18:08 UTC
Labels: question
