### ISSUE TITLE
How to use our own data? 

### ISSUE THREAD

**Issue by AvishkarArjan** [thalesfm/unity-nerf#15] opened 2024-02-14 06:44 UTC
I saw that the .npz file format needs to undergo some sort of binary serialization to be viewed in Unity, but how do we do that? 

Also the files in resources.zip contain  .bin files, however the project page refers to some  .proto file format. How does that work? 

Also pls tell how can I train my own model, perform binary serialization, and generate the  .unity scene file, and view it in unity? 
Plssss it would be really appreciated.

**Comment by thalesfm** [comment] 2024-02-16 17:32
Hi Avishkar,

Yes, for this current version of the project the `.npz` files have to go through a conversion + binary serialization process before they can viewed in the editor (this is all done manually using an external Python script).

Unfortunately I had to put the development of the project on hold due to other demands, but once I return to it hopefully I can make this process much more streamlined/automated.

In regards to the training process I'd have to refer you to PlenOctrees' own documentation ([link](https://github.com/sxyu/plenoctree)).

**Comment by thalesfm** [comment] 2024-02-16 17:57
Duplicate of #16

**Closed by thalesfm** 2024-02-16 17:57 UTC
Labels: question

**Comment by AvishkarArjan** [comment] 2024-02-19 11:17
I see. You've done a great work here. Maybe if you could refer me any sources for me to understand the conversion+binary serialisation process, so that maybe i could work on a script of my own, it would be a great help. Thanks .

**Comment by thalesfm** [comment] 2024-02-23 18:06
Sections 3.2 and 3.3 of the [Tech Report](https://github.com/thalesfm/unity-nerf/blob/691b7019ec25ffb585f99a38f3ec803183d14ae5/Docs/Tech-Report.pdf) explain the format of the data structure and the binary serialization process in more detail if you're interested in the specifics of the process.

But as I said, hopefully I can make this conversion process automatic (or even remove it entirely) in future releases of the project, so those technical details probably won't be as relevant then.
